
---
- hosts: rpi
  vars:
    repo_path: "gitd"
    local_user: "pi"
    local_group: "pi"
  become: yes

  tasks:
    - import_tasks: packages.yml 
    - import_tasks: gitrepo.yml
    - import_tasks: asdf_setup.yml

