
---
- hosts: ubuntu_tc
  vars:
    repo_path: "gitrp"
    local_user: "alastair"
    local_group: "alastair"
  become: yes

  tasks:
    - import_tasks: packages.yml 
    - import_tasks: gitrepo.yml

